#BSUB -J convert_to_vcf[1-22]
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 4
#BSUB -M 50
#BSUB -R rusage[mem=200]
#BSUB -N
#BSUB -B
#BSUB -u whwu1@mdanderson.org

module add plink

cd /rsrch5/home/epi/bhattacharya_lab/data/TCGA/Prostate_Cancer/genotypes
i=$LSB_JOBINDEX
PREFIX="${i}.Prostate_Cancer"
plink2 --bfile $PREFIX --recode vcf --out /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/vcf/PRAD/${i}.Prostate_Cancer.vcf

echo "Converted ${PREFIX} to ${i}.Prostate_Cancer.vcf"
