#BSUB -J cis_qtl
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 2
#BSUB -M 50
#BSUB -R rusage[mem=100]
#BSUB -u whwu1@mdanderson.org

#vcf and bed are zipped and tabix indexed. bed needed to be sorted based on first and second column before zip
module add qtltools          #    --qtl /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/qtl/input/short_cov_overlap.txt \

#QTLtools correct \
#    --bed /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_coding_overlap_sorted.bed.gz \
#    --normal \
#    --out /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_coding_overlap_sorted_normalized.bed

QTLtools trans --vcf /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/vcf/PRAD/PRAD_merged_renamed_filtered.vcf.gz \
             --bed /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_coding_overlap_sorted_normalized.bed.gz \
             --cov /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_cov_overlap_V250.txt \
             --out /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/trans_qtl/significant_output_trans_qtl_protein_coding.txt \
             --nominal 1e-6
             --normal
