#BSUB -J PRAD_transqtl_colocalization
#BSUB -W 24:00
#BSUB -q medium 
#BSUB -n 8
#BSUB -M 50
#BSUB -R rusage[mem=400]
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log

module add plink
module add qtltools
module add tabix

Rscript /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/scripts/ncRNA_QTL/PRAD_trans_qtl_colocalization.R
