#BSUB -J cis_qtl[1-5]
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 5
#BSUB -M 50
#BSUB -R rusage[mem=250]
#BSUB -u whwu1@mdanderson.org

#vcf and bed are zipped and tabix indexed. bed needed to be sorted based on first and second column before zip
module add qtltools          #    --qtl /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/qtl/input/short_cov_overlap.txt \

#QTLtools correct \
#    --bed /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_coding_overlap_sorted.bed.gz \
#    --normal \
#    --out /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_coding_overlap_sorted_normalized.bed

COV_FILES=(
    "short_cov_overlap_V250.txt"
    "short_cov_overlap_V125.txt"
    "short_cov_overlap_V150.txt"
    "short_cov_overlap_V175.txt"
    "short_cov_overlap_V200.txt"
)
COV_FILE=${COV_FILES[$((LSB_JOBINDEX-1))]}
#COV_FILE="short_cov_overlap_V25.txt"

VCF=/rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/vcf/PRAD/PRAD_merged_chr_short.vcf.gz
BED=/rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_non_coding_overlap_sorted_normalized.bed.gz
COV_DIR=/rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input
OUT_DIR=/rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/cis_qtl

BASENAME=$(basename "$COV_FILE" .txt)
OUT_FILE=${OUT_DIR}/cis_qtl_${BASENAME}.txt

# Run QTLtools
QTLtools cis \
  --vcf "$VCF" \
  --bed "$BED" \
  --cov "${COV_DIR}/${COV_FILE}" \
  --out "$OUT_FILE" \
  --nominal 1e-6 \
  --normal


#QTLtools cis --vcf /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/vcf/PRAD/PRAD_merged_renamed_filtered.vcf.gz \
#             --bed /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_non_coding_overlap_sorted_normalized.bed.gz \
#             --cov /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/input/short_cov_overlap_V250.txt \
#             --out /rsrch5/home/epi/bhattacharya_lab/projects/ncRNA_QTL/PRAD_qtl/significant_output_cis_qtl_non_protein_coding.txt \
#             --nominal 1e-6
#             --normal
